import SplashCursor from "@/components/SplashCursor";
import "./globals.css";
export const metadata = {
  title: "Team 99",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <SplashCursor />
        {children}
      </body>
    </html>
  );
}
